float64[] iq
float64[] q_dot
float64[] q_ddot
float64[] tau

float64[] alpha_d0
float64[] alpha_d1
float64[] alpha_inertial
float64[] alpha_kt

float64[] red_ratio

float64[] K_d0_cal
float64[] K_d1_cal
float64[] K_t_cal
float64[] rotor_MoI_cal

float64[] K_d0_ig
float64[] K_d1_ig
float64[] K_t_ig
float64[] rotor_MoI_ig

float64[] K_d0_nom
float64[] K_d1_nom
float64[] K_t_nom
float64[] rotor_MoI_nom

float64[] sol_millis

float64[] lambda
float64[] lambda_des

bool[] cal_mask
bool[] cal_mask_des

string[] jnt_names
